name: Biome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  run_biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: 'latest'
          working-dir: "/"
      - name: Run Biome chrome-extension
        run: biome ci ./apps/chrome-extension
      - name: Run Biome dodom
        run: biome ci ./packages/dodom
